config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope :demos do
    resource :book_search, only: [:show]
    resource :calendar, only: [:show], path: "/calendar/:date"
    resources :calendar_events, only: [:create, :update]
    resource :chat, only: [:show]
    resource :geo_selector, only: [:show]
    resource :gravatar, only: [:show]
    resource :permalink, only: [:show]
    resource :reverse_text, only: [:show]
    resource :snake, only: [:show]
    resource :tabular, only: [:show]
    resource :time_series, only: [:show]
    resource :todo, only: [:show]
    resource :validation, only: [:show]
  end

  resources :demos, only: [:index]
  root "demos#index"
end

app/controllers/calendars_controller.rb
# frozen_string_literal: true

class CalendarsController < ApplicationController
  def show
    @start_date ||= Date.parse(params[:date])
    @start_date = @start_date.to_date.beginning_of_month
    date_range = (@start_date..@start_date.end_of_month)
    @dates = date_range.to_a
    @dates.prepend(@dates.first - 1) until @dates.first.sunday?
    @dates.append(@dates.last + 1) until @dates.last.saturday?
    @calendar_events = CalendarEvent.where(occurs_at: date_range).order(:occurs_at).group_by(&:occurs_at_date)
  end
end

app/helpers/calendars_helper.rb
# frozen_string_literal: true

module CalendarsHelper
end

app/views/calendars/_calendar_event_modal.html.erb
<div class="modal" tabindex="-1" style="display:block">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= @calendar_event.occurs_at.strftime "%A %B, %e %Y" %></h5>
        <button type="button" class="close" data-reflex="click->CalendarReflex#default_reflex">
          <span>&times;</span>
        </button>
      </div>
      <%= form_with model: @calendar_event, html: { data: { controller: "application", action: "ajax:success->application#reload" } } do |f| %>
        <%= f.hidden_field :occurs_at %>
        <div class="modal-body">
          <div class="btn-group mt-3" data-controller="button-group" data-reflex-permanent>
            <%= f.hidden_field :hour, data: { target: "button-group.input" } %>
            <% (1..12).each do |i| %>
              <%= tag.button i, type: "button",
                class: css("btn btn-light", "active": @calendar_event.occurs_at.strftime("%I").to_i == i),
                data: { action: "click->button-group#select" } %>
            <% end %>
          </div>
          <div class="btn-group mt-2" data-controller="button-group" data-reflex-permanent>
            <%= f.hidden_field :meridian, data: { target: "button-group.input" } %>
            <%= tag.button "AM", type: "button",
              class: css("btn btn-light", "active": @calendar_event.occurs_at.strftime("%p") == "AM"),
              data: { action: "click->button-group#select" } %>
            <%= tag.button "PM", type: "button",
              class: css("btn btn-light", "active": @calendar_event.occurs_at.strftime("%p") == "PM"),
              data: { action: "click->button-group#select" } %>
          </div>
          <div class="form-group my-3">
            <%= f.text_area :description, placeholder: "Description for this event...", class: "form-control", rows: 3,
              data: { reflex: "input->CalendarReflex#validate_calendar_event", id: @calendar_event.id, date: @calendar_event.occurs_at.to_date.iso8601  } %>
          </div>
          <%= f.submit "Save", class: "btn btn-primary", disabled: @calendar_event.invalid? %>
          <button type="button" class="btn btn-link" data-reflex="click->CalendarReflex#default_reflex">Cancel</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/calendars/_demo.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h2><%= @start_date.strftime("%B %Y") %></h2>
  <div class="text-success" hidden data-activity-indicator>
    <div class="spinner-border spinner-border-sm"></div>
    <span>Loading...</span>
  </div>
  <div>
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
      <%= link_to calendar_path(@start_date.advance(months: -1).iso8601), title: "Previous", class: "btn btn-light" do %>
        <i class="fas fa-chevron-left"></i>
      <% end %>
      <%= link_to calendar_path(@start_date.advance(months: 1).iso8601), title: "Next", class: "btn btn-light" do %>
        <i class="fas fa-chevron-right"></i>
      <% end %>
    </div>
    <%= link_to "Today", calendar_path(Date.current.beginning_of_month.iso8601), class: "btn btn-light" %>
  </div>
</div>

<table id="calendar-<%= @start_date.iso8601 %>" class="table table-bordered mt-2">
  <thead class="thead-dark">
    <tr class="text-center">
      <% Date::DAYNAMES.each do |name| %>
        <th style="width:14%" ><%= name %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @dates.each_slice(7) do |week| %>
      <tr>
        <% week.each do |date| %>
          <%= tag.td class: css("", "bg-warning-lighter": date.today?, "bg-secondary-lightest": @start_date.month != date.month),
            data: { reflex: "click->CalendarReflex#new_calendar_event", date: date.iso8601 } do %>
            <%= tag.span date.day, class: "lead" %>
            <div class="mt-2" style="height:65px; overflow-y:scroll">
              <% (@calendar_events[date] || []).each do |calendar_event| %>
                <div class="bg-white py-1 px-2 border mb-1" data-controller="application" data-action="click->application#default_reflex">
                  <%= link_to "#", class: "float-right text-danger", data: { reflex: "click->CalendarReflex#destroy_calendar_event", id: calendar_event.id} do %>
                    <i class="fas fa-window-close"></i>
                  <% end %>
                  <small class="d-block text-secondary">
                    <%= calendar_event.occurs_at.strftime "%l %p" %>
                  </small>
                  <div>
                    <%= truncate calendar_event.description, length: 24 %>
                    <small><%= link_to "Edit...", "#", class: "ml-2", data: { reflex: "click->CalendarReflex#edit_calendar_event", id: calendar_event.id } %></small>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render "/calendars/calendar_event_modal" if @calendar_event %>

app/views/calendars/show.html.erb
<%= content_for :demo_title, "Calendar" %>
<%= content_for :demo_summary, "Simple UTC based calendar with events" %>
<%= render_demo "/calendars/demo" %>

<%= render_gists(
  "app/javascript/controllers/button_group_controller.js",
  "app/views/calendars/_demo.html.erb",
  "app/views/calendars/_calendar_event_modal.html.erb",
  "app/controllers/calendars_controller.rb",
  "app/controllers/calendar_events_controller.rb",
  "app/models/calendar_event.rb",
  "app/reflexes/calendar_reflex.rb"
) %>